version: 0.2
env:
  variables:
    VAR1: "val1"
phases:
  install:
  dsdsd
    commands:
      - echo Entered the install phase...
      -  pip install --user yamllint
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
name: name1
