# Simple workflow to demonstrate using AWS CodeBuild runner from GitHub Action
name: AWS-OIDC-Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run custom steps
        run: |
          pwd
          id
          ls -al
          python --version
          /root/.local/bin/yamllint yamls
          sleep 2
  
