# Simple workflow to demonstrate using AWS CodeBuild runner from GitHub Action
name: AWS-OIDC-Workflow
on:
  workflow_dispatch:
env:
  AWS_REGION: "us-east-1"
  
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run custom steps
        run: |
          pwd
          id
          ls -al
          python --version
          sleep 2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::291912718832:role/oidc-github-aws
          role-session-name: GitHub-To-AWS-OIDC
          aws-region: us-east-1
      - name: run aws command
        run: aws codebuild list-projects
          
