# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: 
      - codebuild-github-runner-01-${{ github.run_id }}-${{ github.run_attempt }}
      #- codebuild-test-project-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!; exit 1
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run custom steps
        run: |
          pwd
          id
          ls -al
          python --version
  #test:
    #runs-on: ubuntu-latest
    #runs-on: codebuild-github-runner-${{ github.run_id }}-${{ github.run_attempt }}
    #steps:
    #  - name: Run a multi-line script
    #    run: |
    #      echo Add other actions to test
    
