name: Caller-Get-Environments

on:
  workflow_dispatch:

jobs:
  get-environments:
    uses: sp-org-1/repo-1/.github/workflows/reusable.yaml@master
  deploy:
    runs-on: ubuntu-latest
    needs: get-environments
    strategy:
      matrix:
        environment: ${{ fromJson(needs.get-environments.outputs.names) }}
    environment:
      name: ${{ matrix.environment }}
    steps:
      - run: echo "${{ vars.ENV_VAR }}"
