name: Call-JS-Action
on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: sp-org-1/javascript-action@main
        with:
          person: 'Pawar'
        env:
          VAR: value
        
