name: Get-Env-Specific-Variable

on:
  workflow_dispatch:
jobs:
  get-env-variable:
    runs-on: windows-latest
    environment: dev
    outputs:
      VAULT_NS: ${{ steps.get-env-var.outputs.NS }}
    steps:
      - name: Get env variable
        id: get-env-var
        run: |
          Write-Output "NS=${{ vars.VAULT_SUBNAMESPACE }}" >> "$env:GITHUB_OUTPUT"
  
  print-env-variable:
    runs-on: windows-latest
    needs: get-env-variable
    steps:
      - name: Print env variable
        run: |
          Write-Output "${{ needs.get-env-variable.outputs.VAULT_NS }}"
