name: Get-Env-Specific-Variable

on:
  workflow_dispatch:
jobs:
  get-env-variable:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      VAULT_NS: ${{ steps.get-env-var.outputs.NS }}
    steps:
      - name: Get env variable
        id: get-env-var
        run: echo "NS=${{ vars.VAULT_SUBNAMESPACE }}" >> "$GITHUB_OUTPUT"
  
  print-env-variable:
    runs-on: ubuntu-latest
    needs: get-env-variable
    steps:
      - name: Print env variable
        run: echo ${{ needs.get-env-variable.outputs.VAULT_NS }}
