name: Get-Env-Specific-Variable

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage
    outputs:
      VAULT_NS: ${{ steps.get-env-var.outputs.NS }}
    steps:
      - name: Run a one-line script
        id: get-env-var
        run: echo "NS=${{ vars.VAULT_SUBNAMESPACE }}" >> "$GITHUB_OUTPUT"
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run a one-line script
        id: get-env-var
        run: echo ${{ needs.build.outputs.VAULT_NS }}
