name: Get-Env-Specific-Variable

on:
  workflow_dispatch:
jobs:
  get-env-variable:
    runs-on: windows-latest
    environment: stage
    outputs:
      VAULT_NS: ${{ vars.VAULT_SUBNAMESPACE }}
    steps:
      - name: Get env variable
        id: get-env-var
        run: |
          Write-Output "Get env variable"
  
  print-env-variable:
    runs-on: windows-latest
    needs: get-env-variable
    steps:
      - name: Print env variable
        run: |
          Write-Output "${{ needs.get-env-variable.outputs.VAULT_NS }}"
