name: Windows-Variable-List-API
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      #- name: Generate access token
      #  id: generate-access-token
      #  uses: actions/create-github-app-token@v1
      #  with:
      #    app-id: ${{ vars.APP_ID }}
      #    private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Build
        shell: pwsh
        run: |
          .\scripts\test.ps1 -accessToken Z2hwX05oWG9YZTVud1hXMjJHdUR0T0V0b2FiaXc1MDNiUjJ6dHFBago= -orgName sp-org-1 -repoName repo-1
