name: Get environments
on: 
  workflow_dispatch: 
  workflow_call:
jobs:
  get_envs:
    runs-on: ubuntu-latest
    steps:
      - name: Get environments
        uses: octokit/request-action@v2.3.0
        id: get_env
        with:
          route: GET /repos/${{ github.repository }}/environments?per_page=100 # If we ever have >100 deployments, we'll need to paginate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set output
        id: set_env
        run: echo "names=$(echo $NAMES | jq -c '[.[] | select(startswith("[${{ github.ref_name }}]"))]' -j)"
        env:
          NAMES: ${{ toJson(fromJson(steps.get_env.outputs.data).environments.*.name) }}
