name: Windows-Variable-List-API
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: pwsh
        run: |
          .\scripts\test.ps1 -accessToken Z2hwXzFvZFppcGJZbEM1VUJwaUVEN0d1dXBDSkxHSkFMZDNpWDN1Vgo= -orgaName sp-org-1
