name: Hashicorp-Vault-Get-Creds

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      value:
        description: Secret value
        value: ${{ env.MY_SECRET }}
jobs:
  vault:
    runs-on: ubuntu-latest 
    steps:
      - uses: 'hashicorp/hcp-auth-action@v0'
        with:
          client_id: ${{ secrets.HCP_CLIENT_ID }}
          client_secret: ${{ secrets.HCP_CLIENT_SECRET }}
      - uses: 'hashicorp/hcp-setup-action@v0'
        with:
          version: 'latest'
      - name: 'Read a secret and inject as an environment variable'
        run: |
          MY_SECRET=$(hcp vault-secrets secrets open \
            --app=WebApp --format=json apppassword | jq -r '.static_version.value')
          echo $MY_SECRET
          echo "::add-mask::$MY_SECRET"
          echo "MY_SECRET=$MY_SECRET" >> $GITHUB_ENV
  
