name: Caller-Get-Hashicorp

on:
  workflow_dispatch:

jobs:
  get-secret:
    uses: sp-org-1/repo-1/.github/workflows/hashicorp-vault.yaml@master
    secrets: inherit
    with:
      key: dppassword
  deploy:
    runs-on: ubuntu-latest
    needs: get-secret
    steps:
      - run: echo "${{ needs.get-secret.outputs.value }}"
