name: Hashicorp-Vault-Get-Creds

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
      #- codebuild-github-runner-01-${{ github.run_id }}-${{ github.run_attempt }}
      #- buildspec-override:true
    steps:
      - uses: actions/checkout@v4
      - name: Get runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Get github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  vault:
    runs-on: ubuntu-latest 
    steps:
      - uses: 'hashicorp/hcp-auth-action@v0'
        with:
          client_id: ${{ secrets.HCP_CLIENT_ID }}
          client_secret: ${{ secrets.HCP_CLIENT_SECRET }}
      - uses: 'hashicorp/hcp-setup-action@v0'
        with:
          version: 'latest'
      - name: 'Read a secret and inject as an environment variable'
        run: |
          MY_SECRET=$(hcp vault-secrets secrets open \
            --app=cli --format=json foo | jq -r '.static_version.value')
          echo "::add-mask::$MY_SECRET"
          echo "MY_SECRET=$MY_SECRET" >> $GITHUB_ENV
  
