name: Hashicorp-Vault-Get-Creds
on:
  workflow_call:
    outputs:
      value:
        description: Secret value
        value: ${{ jobs.vault.outputs.value }}
jobs:
  vault:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.get-secret.oututs.value }}
    steps:
      - uses: 'hashicorp/hcp-auth-action@v0'
        with:
          client_id: ${{ secrets.HCP_CLIENT_ID }}
          client_secret: ${{ secrets.HCP_CLIENT_SECRET }}
      - uses: 'hashicorp/hcp-setup-action@v0'
        with:
          version: 'latest'
      - name: 'Read a secret and inject as an environment variable'
        id: get-secret
        run: |
          VALUE=$(hcp vault-secrets secrets open \
            --app=WebApp --format=json apppassword | jq -r '.static_version.value')
          echo $VALUE
          echo "::add-mask::$VALUE"
          echo "value=$VALUE" >> $GITHUB_OUTPUT
  
