name: Process environments
on: 
  workflow_dispatch: 
jobs:
  #get-envs:
  #  uses: ./.github/workflows/get-environments.yaml@master
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, stage]
        #environment:${{ fromJson(needs.get_envs.outputs.names) }}
    environment:
      name: ${{ matrix.environment }}
    steps:
      - run: echo "${{ vars.ENV_VAR }}"
