name: PS-Encrypt-Decrypt
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Run1
        run: |
          $encKey = ${{ secrets.ENCR_KEY }}
          echo $encKey
          $str = "Santosh"
          # converting string to bytes array
          $bytesArr = [System.Text.Encoding]::UTF8.GetBytes($str)
          # Print the bytes array
          $bytesArr
          # Convert byte to string
          $str2 = [System.Text.Encoding]::UTF8.GetString($bytesArr)
          # Print the string
          $str2
          
          $bytesArr = @(56, 34, 239, 191, 189, 42, 54, 33, 239, 191, 189, 34, 35, 43)
          
          
          #$b = [System.Text.Encoding]::UTF8.GetBytes($str)
          #echo $b
          $b = (3,4,2,3,56,34,254,222,1,1,2,23,42,54,33,233,1,34,2,7,6,5,35,43)
          echo "======="
          echo $b
          # Convert byte to string
          $str2 = [System.Text.Encoding]::UTF8.GetString($b)
          echo $str2
          $text = "Hello, this is a secret message"
          $secureString = ConvertTo-SecureString $text -AsPlainText -Force
          Write-Output $secureString
          $encryptedText = ConvertFrom-SecureString $secureString -Key $bytesArr
          Write-Output $encryptedText
          
          $secureString = ConvertTo-SecureString $encryptedText -Key $bytesArr
          $plainText = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
              [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureString)
          )
          Write-Output $plainText
