name: Reusable-Get-Environments
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      envs:
        description: "The second output string"
        value: ${{ jobs.get-environments.outputs.envs }}
jobs:
  get-environments:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      envs: ${{ steps.set-output.outputs.names }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/${{ github.repository }}/environments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set output
        id: set-output
        run: echo 'names=${{ toJson(fromJson(steps.get_latest_release.outputs.data).environments.*.name) }}' | tr -d '\n'  >> $GITHUB_OUTPUT; cat $GITHUB_OUTPUT
        
