# Workflow to review commit or PR using GenAI agent
name: Review-Comment-PR
on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'releases/**'
  workflow_dispatch:
permissions: write-all
jobs:
  invoke-agent:
    #runs-on: ubuntu-latest
    runs-on: 
      - codebuild-github-runner-01-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get change type
        id: get-change-type
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Invoke Agent for Commit
        if: github.event_name == 'push' && ! contains(github.event.head_commit.message, 'skip-review')
        uses: sp-org-1/invoke-aws-bedrock-agent@53274093a9a8d20ee38715ac93219ffc2005802d
        with:
          change-type: 'Comment'
      - name: Invoke Agent for PR
        if: startsWith(github.ref, 'refs/pull/')
        uses: sp-org-1/invoke-aws-bedrock-agent@53274093a9a8d20ee38715ac93219ffc2005802d
        with:
          change-type: 'PR'
