# Workflow to review commit or PR using GenAI agent
name: Review-Comment-PR
on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'releases/**'
  workflow_dispatch:
permissions: write-all
env:
  DEBUG: 'true'
jobs:
  invoke-agent:
    runs-on: ubuntu-latest
    #runs-on: 
      #- codebuild-github-runner-01-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Invoke Agent for Commit
        uses: sp-org-1/invoke-aws-bedrock-agent@v1
        env:
          PR_REVIEW_AGENT_ID: ${{ vars.PR_REVIEW_AGENT_ID }}
          PR_REVIEW_AGENT_ALIAS_ID: ${{ vars.PR_REVIEW_AGENT_ALIAS_ID }}
        with:
          change-type: ${{ github.event_name == 'push' && github.event.created == false && !contains(github.event.head_commit.message, 'skip-review') && 'Comment' || 'PR' }}
          debug: ${{ env.DEBUG }}
      
