# Workflow to review commit or PR using GenAI agent
name: Review-Comment-PR
on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'releases/**'
  workflow_dispatch:
permissions: write-all
jobs:
  invoke-agent:
    runs-on: ubuntu-latest
    #runs-on: 
      #- codebuild-github-runner-01-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: "Test1"
        run: echo ${{ vars.PR_REVIEW_AGENT_ID }}
      - name: Invoke Agent for Commit
        if: github.event_name == 'push' && github.event.created == false && !contains(github.event.head_commit.message, 'skip-review')
        uses: sp-org-1/invoke-aws-bedrock-agent@ef385edc1054a203ac4e96bfad76e0d8d03f59f8
        with:
          change-type: 'Comment'
      - name: Invoke Agent for PR
        if: github.event_name == 'pull_request'
        uses: sp-org-1/invoke-aws-bedrock-agent@ef385edc1054a203ac4e96bfad76e0d8d03f59f8
        with:
          change-type: 'PR'
