# Simple workflow to demonstrate using AWS CodeBuild runner from GitHub Action
name: Review-PR

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'releases/**'
  workflow_dispatch:

jobs:
  #build:
  #  permissions:
  #    id-token: write
  #    contents: read
  #    pull-requests: write
  #  runs-on:
  #    - codebuild-github-runner-01-${{ github.run_id }}-${{ github.run_attempt }}
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Run a one-line script
  #      run: echo Hello, world!
  #    - name: Run a multi-line script
  #      run: |
  #        echo Add other actions to build,
  #        echo test, and deploy your project.
      #- name: Configure AWS credentials
      #  uses: aws-actions/configure-aws-credentials@v4
      #  with:
      #    aws-region: us-east-1
      #    role-to-assume: arn:aws:iam::291912718832:role/service-role/AmazonBedrockExecutionRoleForAgents_LS8YP3KXWPP
      #- name: Run custom steps
      #  run: |
      #    pwd
      #    id
      #    ls -al
      #    python --version
      #    /root/.local/bin/yamllint yamls
          #sleep 30
  invoke-agent:
    permissions:
      contents: read
      pull-requests: read
      repository-projects: read
    #runs-on: ubuntu-latest
    runs-on: 
      - codebuild-github-runner-01-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Test
        run: gh pr list
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Invoke Agent
        uses: sp-org-1/invoke-aws-bedrock-agent@4cbf9a8ce95a5a20af40334a6df391dc73186d2e
