name: Run-Sonarscan

on:
  workflow_dispatch:
jobs:
  get-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Get env variable
        id: get-env-var
        run: |
          echo "Get env variable"
  
