name: Run-Sonarscan

on:
  workflow_dispatch:
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- name: SonarQube Scan
      #  uses: SonarSource/sonarqube-scan-action@v5
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Get Scan Results
        run: |
          python .github/workflows/scripts/get-scan-results.py ${{ secrets.SONAR_TOKEN }}
          
