# Simple workflow to demonstrate using AWS CodeBuild runner from GitHub Action
name: Simple-Workflow

on:
  workflow_dispatch:
    inputs:
      targetTag:
        description: "Select the Target Tag"
        required: true
        default: 'select'
        type: choice
        options:
          - RCM-AHI.APP.PHASE2
          - RCM-AHI.WEB
          - RCM-AHI.APP.LEGACY
          - RCM-AHI.TEST
          - select
      environment:
        description: "Select the Target"
        required: true
        default: "Selection needed"
        type: choice
        options:
          - qa
          - dev
          - mock
          - Selection needed

env:
  environment: ${{ inputs.environment }}
  secrets_path: ${{ endswith(inputs.targetTag, 'PHASE2') && 'phase2' || endswith(inputs.targetTag, 'WEB') && 'web' || endswith(inputs.targetTag, 'TEST') && 'test' || 'legacy' }}_ahi_${{ inputs.environment }}

jobs:
  build:
    runs-on: ubuntu-latest 
      #- codebuild-github-runner-01-${{ github.run_id }}-${{ github.run_attempt }}
      #- buildspec-override:true
    steps:
      - uses: actions/checkout@v4
      - name: Get runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Get github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ inputs.environment }}
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo ${{ env.secrets_path }}
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
