# Simple workflow to demonstrate using AWS CodeBuild runner from GitHub Action
name: Test-Workflow

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Get runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Get github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
