name: Windows-Dynamic-Variable-Value
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate access token
        id: generate-access-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Run1
        run: |
          $myList = @{}
          $myList.add( "ONE", 1)
          $myList.add( "TWO", 2)
          gh variable list
          #gh pr list
          foreach ($h in $myList.Keys) {
            Write-Output "*** $h";
            gh variable get $h;
            #Write-Output "******** ${{ vars[format('{0}', '$h')] }}";
          };
          $headers = @{
            "Authorization" = [String]::Format("token {0}", $env:GITHUB_TOKEN)
            "Content-Type"  = "application/json"
          }

          $callUri = "https://api.github.com/orgs/sp-org-1/repos"
          Write-Output $callUri
          $repoVariables = Invoke-RestMethod -Method get -Uri $callUri -Headers $headers 
          Write-Output $repoVariables

          $callUri = "https://api.github.com/repos/sp-org-1/repo-1/actions/variables/APP_ID"
          Write-Output $callUri
          $repoVariables = Invoke-RestMethod -Method get -Uri $callUri -Headers $headers 
          Write-Output $repoVariables

        env:
          #GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate-access-token.outputs.token }}
