name: Windows-Dynamic-Variable-Value
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run1
        run: |
          $myList = @{}
          $myList.add( "ONE", 1)
          $myList.add( "TWO", 2)
          $myList.add( "THREE", 3)
          gh variable list
          foreach ($h in $myList.Keys) {
            Write-Output "*** $h";
            #Write-Output "******** ${{ vars[format('{0}', '$h')] }}";
          };
        env:
          GH_TOKEN: ${{ github.token }}
