name: Windows-Matrix-Conditional
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        host: ['host1', 'host2', '']
    runs-on: windows-latest 
    steps:
      - name: Run1
        env:
          cmd_part: ${{ matrix.host == '' && ' ' || format('-ComputerName {0}', matrix.host) }}
        run: |
          Invoke-Command ${{ env.cmd_part }} -ScriptBlock {
            (Get-Host).Version
          }
