name: Windows-Dynamic-Variable-Value
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Run1
        run: |
          $myList = New-Object Collections.Generic.List[string]
          $myList.Add("one")
          $myList.Add("two")
          $myList.Add("three")
          foreach ($h in $myList.Keys) {
            Write-Output "*** $h";
            #Write-Output "******** ${{ vars[format('{0}', '$h')] }}";
          };
  
