name: Windows-Dynamic-Variable-Value
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Run1
        run: |
          $myList = New-Object Collections.Generic.List[string]
          $myList.add( "one", 1)
          $myList.add( "two", 2)
          $myList.add( "three", 3)
          foreach ($h in $myList.Keys) {
            Write-Output "*** $h";
            #Write-Output "******** ${{ vars[format('{0}', '$h')] }}";
          };
  
